### ISSUE TITLE
Fix callback url behind proxy

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gogs#26]
currently redirects to http instead of https.

Note: running behind caddy, should check proxy headers

**Comment by LeeSmet** [comment]
check the `X-Forwarded-Proto` header

**Comment by arahmanhamdy** [comment]
fixed in gigforks/gitea

The integration flow of itsyou.online with gitea has been changed to use GOTH library. So a lot of issues has been already fixed:
1 - callback urls behind proxy
2 - gitea can redirect user now to the same page he was at before logging
3 - user can use git through https 
4 - We are using the gitea oauth2 standard integration so that less conflicts with common files

**Comment by LeeSmet** [comment]
Original setup:
gogs running behind caddy, caddy acts as a reverseproxy, communication between gogs and caddy is http and not https

result: Because there was no logic in gogs that checked the headers when constructing requests, the callback url was set as `http://...` instead of `https://...`. On iyo, the callback url was set to be `https://...`.
When a user then tries to log in, iyo returns a bad request because the callback passed in the request and the callback set in the api key are different.

**Comment by Dinaamagdy** [comment]
## Software Version 
fixed on gitea https://github.com/gigforks/gitea/issues/3
